server.port=${PORT:8080}

# MySQL (Render / External)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

razorpay.key_id=${RAZORPAY_KEY_ID:dummy}
razorpay.key_secret=${RAZORPAY_KEY_SECRET:dummy}