# =====================
# SERVER
# =====================
server.port=8080

# =====================
# DATASOURCE
# =====================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================
# JPA
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# =====================
# RAZORPAY (TEMP FIX)
# =====================
razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}

# =====================
# ACTUATOR
# =====================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=100MB


# =====================
# FIREBASE
# =====================

{
  "type": "service_account",
  "project_id": "ronex-88c3a",
  "private_key_id": "db94bf2feab6d2f53710ce7b21a81856acdbc787",
  "client_email": "firebase-adminsdk-fbsvc@ronex-88c3a.iam.gserviceaccount.com",
  spring.profiles.active=prod
  "client_id": "110125244529592257785",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40ronex-88c3a.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
